networks:
  image_network:
    name: image_network
    driver: bridge

services:
  #frontend
  frontend:
    image: rywj/frontend:latest
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "80:80"
    networks:
      - image_network
  
  #backend
  backend:
    image: rywj/backend:latest
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "5000:5000"
    networks:
      - image_network
    