# Use the official Node.js runtime as the base image
FROM node:20.16.0-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Expose the application port
EXPOSE 5000

# Set the default command to run the server
CMD ["node", "server.js"]
