name: Build Docker Image
run-name: Quality Gate and Dependency Check
on: 
  push:
    branches:
      - cicd

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run quality gate
        run: |
          echo "Running quality gate checks..."
          # Add your quality gate commands here
          # For example, you can run a linter or static analysis tool
  
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:

      - name: Set up Docker
        uses: docker/setup-docker-action@v2
      
      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/dockerfile
          push: true
          tags: rywj/frontend:latest
      
      - name: Build Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: rywj/backend:latest

  deploy-container:
    name: Deploy Container
    runs-on: self-hosted
    needs: build-docker-image

    steps:
      - name: Deploy Docker Compose
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: ansible/docker.yaml
          inventory: ansible/hosts
          extra_vars: |
            docker_username=${{ secrets.DOCKER_USERNAME }}
            docker_password=${{ secrets.DOCKER_PASSWORD }}
